const htmlExample = 
`<!-- The html code is generated by JS -->
<div class="example">
    <div class="example__view">
        <p class="example__view__text">
            Enter number from 2 to 9
        </p>
        <ul class="example__view__list"></ul>
    </div>

    <form class="example__form">
        <input class="example__form__input"
            type="text"
            required
            pattern="[2-9]"
            maxlength="1">

        <div class="example__form__error">
            <p class="example__form__error__value">
                Enter correct value
            </p>
        </div>

        <div class="example__form__buttons">
            <button class="example__form__buttons__create example-block-item"
                type="submit"
                data-type="create">
                create
            </button>
            <button class="example__form__buttons__delete example-block-item"
                type="submit"
                data-type="delete">
                delete
            </button>
        </div>
    </form>

    <div class="example__nav">
        <ul class="example__nav__list"></ul>
    </div>
</div>
`;

class CodeExample {
    codeWrap_HTML = document.querySelector('.cv__main__code__wrap__examples');
    htmlJS = htmlExample;
    htmlAngular = 'Angular';

    codeExamples = [
        {
            title: 'vanilla JS',
            codeNav: ['HTML', 'CSS', 'JS', 'utile'],
            html: this.htmlJS,
            htmlStrNum: this.calcStringInCode(this.htmlJS),
        },
        {
            title: 'Angular',
            codeNav: ['HTML', 'SCSS', 'TS', 'utile'],
            html: this.htmlAngular,
            htmlStrNum: this.calcStringInCode(this.htmlAngular),
        },

    ];

    constructor() {
        this.renderCodeExample();
    }

    renderCodeExample() {

        this.codeExamples.forEach((code, index) => {

            const div = document.createElement('div');
            div.classList.add('cv__main__code__wrap__examples__code-example');

            const nav = () =>
                code.codeNav.reduce((prev, curr, index) => {
                    if (index === 0) {
                        prev += `<li class="cv__main__code__wrap__examples__code-example__nav__item active-item" data-name="${curr}">${curr}</li>`;
                    } else {
                        prev += `<li class="cv__main__code__wrap__examples__code-example__nav__item" data-name="${curr}">${curr}</li>`;
                    }
                    return prev;
                }, ``);

            const view = `
              <h4 class="cv__main__code__wrap__examples__code-example__title">
                ${code.title}
              </h4>
              <ul class="cv__main__code__wrap__examples__code-example__nav">
                 ${nav()}
              </ul>
              <div class="cv__main__code__wrap__examples__code-example__code">

              <div class="cv__main__code__wrap__examples__code-example__code__nunber">
              <pre><code>${this.createcodeExamplestringNumber(code.htmlStrNum)}</code></pre>
              </div>
              <div class="cv__main__code__wrap__examples__code-example__code__text"><pre><code class="cv__main__code__wrap__examples__code-example__code__text__html"></code></pre></div>
              </div>
            `;

            div.innerHTML = view;
            this.codeWrap_HTML.appendChild(div);
            const htmlCode = document.querySelectorAll('.cv__main__code__wrap__examples__code-example__code__text__html');
            htmlCode[index].textContent = code.html;
        });
    }

    createcodeExamplestringNumber(number) {
        let strNumber = 0;
        let numbers = ``;
        while (strNumber < number) {
            numbers += `${++strNumber}<br>`;
        }
        return numbers;
    }

    calcStringInCode(code) {
        return code.split(`\n`).length;
    }

}

const codeExample = new CodeExample();
