const htmlExampleJS =
    `<!-- The html code is generated by JS -->
<div class="example">
  <div class="example__view">
    <p class="example__view__text">
      Enter number from 2 to 9
    </p>
    <ul class="example__view__list"></ul>
  </div>

  <form class="example__form">
    <input class="example__form__input"
      type="text"
      required
      pattern="[2-9]"
      maxlength="1">

    <div class="example__form__error">
      <p class="example__form__error__value">
        Enter correct value
      </p>
    </div>

    <div class="example__form__buttons">
      <button class="example__form__buttons__create example-block-item"
        type="submit"
        data-type="create">
        create
      </button>
      <button class="example__form__buttons__delete example-block-item"
        type="submit"
        data-type="delete">
        delete
      </button>
    </div>
  </form>

  <div class="example__nav">
    <ul class="example__nav__list"></ul>
  </div>
</div>
`;

const cssExampleJS =
    `.example {
    max-width: 600px;
    width: 100%;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: space-between;
    padding: 20px;
    background: var(--mainColorDark);
  }
  
  .example__view {
    width: 100%;
    height: 120px;
    display: flex;
    align-items: center;
    justify-content: center;
    border: 2px solid #ffffff;
    border-top-left-radius: 30px;
    border-bottom-right-radius: 30px;
    color: #ffffff;
  }
  
  .example__view__text {
    font-size: 32px;
  }
  
  .example__view__list {
    display: none;
  }
  
  .example__view__list__list-item {
    padding: 0 10px;
    font-size: 50px;
    color: #ffffff;
  }
  
  .example__form {
    height: 150px;
    margin-top: 20px;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: space-around;
  }
  
  .example__form__input {
    width: 50px;
    height: 50px;
    padding: 10px;
    border-radius: 10px;
    font-size: 36px;
    text-align: center;
    line-height: 1;
    color: var(--mainColorFont);
  }
  
  .example__form__input:invalid {
    background-color: var(--mainColorLight);
  }
  
  .example__form__buttons__create,
  .example__form__buttons__delete {
    text-transform: uppercase;
    margin: 0 10px;
    padding: 6px 10px;
    border: 1px solid var(--additionalColorLight);
    border-radius: 4px;
    background: var(--additionalDark);
    color: var(--additionalColorLight);
    cursor: pointer;
    transition: .3s;
  }
  
  .example__form__buttons__create:hover,
  .example__form__buttons__delete:hover {
    background-color: var(--mainColorDark);
    color: #ffffff;
  }
  
  .example__form:invalid .example__form__buttons__create {
    opacity: .4;
    pointer-events: none;
  }
  
  .example__form__error {
    height: 40px;
    display: flex;
    flex-direction: column;
    align-items: center;
  }
  
  .example__form__error__value {
    opacity: 0;
    color: #ffffff;
    transition: .3s;
  }
  
  .example__form:invalid .example__form__error__value {
    opacity: 1;
  }
  
  .example__nav {
    width: 100%;
    height: 50px;
    display: flex;
  }
  
  .example__nav__list__list-item {
    padding: 2px 5px;
    background: var(--mainColorLight2);
    border-radius: 4px;
    cursor: pointer;
    transition: .3s;
  }
  
  .example__nav__list__list-item:hover {
    background: #ffffff;
  }
  
  .example-block-item {
    opacity: 0.5;
    pointer-events: none;
  }`;

export { htmlExampleJS, cssExampleJS };
