const htmlExampleJS =
    `<!-- The html code is generated by JS -->
<div class="example">
  <div class="example__view">
    <p class="example__view__text">
      Enter number from 2 to 9
    </p>
    <ul class="example__view__list"></ul>
  </div>

  <form class="example__form">
    <input class="example__form__input"
      type="text"
      required
      pattern="[2-9]"
      maxlength="1">

    <div class="example__form__error">
      <p class="example__form__error__value">
        Enter correct value
      </p>
    </div>

    <div class="example__form__buttons">
      <button class="example__form__buttons__create example-block-item"
        type="submit"
        data-type="create">
        create
      </button>
      <button class="example__form__buttons__delete example-block-item"
        type="submit"
        data-type="delete">
        delete
      </button>
    </div>
  </form>

  <div class="example__nav">
    <ul class="example__nav__list"></ul>
  </div>
</div>
`;

const cssExampleJS =
    `.example {
    max-width: 600px;
    width: 100%;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: space-between;
    padding: 20px;
    background: var(--mainColorDark);
  }
  
  .example__view {
    width: 100%;
    height: 120px;
    display: flex;
    align-items: center;
    justify-content: center;
    border: 2px solid #ffffff;
    border-top-left-radius: 30px;
    border-bottom-right-radius: 30px;
    color: #ffffff;
  }
  
  .example__view__text {
    font-size: 32px;
  }
  
  .example__view__list {
    display: none;
  }
  
  .example__view__list__list-item {
    padding: 0 10px;
    font-size: 50px;
    color: #ffffff;
  }
  
  .example__form {
    height: 150px;
    margin-top: 20px;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: space-around;
  }
  
  .example__form__input {
    width: 50px;
    height: 50px;
    padding: 10px;
    border-radius: 10px;
    font-size: 36px;
    text-align: center;
    line-height: 1;
    color: var(--mainColorFont);
  }
  
  .example__form__input:invalid {
    background-color: var(--mainColorLight);
  }
  
  .example__form__buttons__create,
  .example__form__buttons__delete {
    text-transform: uppercase;
    margin: 0 10px;
    padding: 6px 10px;
    border: 1px solid var(--additionalColorLight);
    border-radius: 4px;
    background: var(--additionalDark);
    color: var(--additionalColorLight);
    cursor: pointer;
    transition: .3s;
  }
  
  .example__form__buttons__create:hover,
  .example__form__buttons__delete:hover {
    background-color: var(--mainColorDark);
    color: #ffffff;
  }
  
  .example__form:invalid .example__form__buttons__create {
    opacity: .4;
    pointer-events: none;
  }
  
  .example__form__error {
    height: 40px;
    display: flex;
    flex-direction: column;
    align-items: center;
  }
  
  .example__form__error__value {
    opacity: 0;
    color: #ffffff;
    transition: .3s;
  }
  
  .example__form:invalid .example__form__error__value {
    opacity: 1;
  }
  
  .example__nav {
    width: 100%;
    height: 50px;
    display: flex;
  }
  
  .example__nav__list__list-item {
    padding: 2px 5px;
    background: var(--mainColorLight2);
    border-radius: 4px;
    cursor: pointer;
    transition: .3s;
  }
  
  .example__nav__list__list-item:hover {
    background: #ffffff;
  }
  
  .example-block-item {
    opacity: 0.5;
    pointer-events: none;
  }`;

  const jsExamlle =
`class Example {
  frame = document.querySelector('.frame__body');
  form = null;
  formInput = null;
  createArrayButton = null;
  deleteArrayButton = null;
  numberListVeiw = null;
  messageVlew = null;

  navList = [
    '  ',
  ];

  result = [];

  constructor() {
    this.render();
    this.afteRender();
  }

  render() {
    const viewExample = '<!-- html code generated by JS -->';
    this.frame.innerHTML = viewExample;
    this.renderNavList();
  }

  afteRender() {
    this.form = document.querySelector('.example__form');
    this.formInput = document.querySelector('.example__form__input');
    this.createArrayButton = document.querySelector('.example__form__buttons__create');
    this.numberListVeiw = document.querySelector('.example__view__list');
    this.messageVlew = document.querySelector('.example__view__text');
    this.deleteArrayButton = document.querySelector('.example__form__buttons__delete');

    this.formInput.addEventListener('focus', () => this.createArroyButton_HTMLElem.classList.remove('example-block-item'));
    this.form.addEventListener('submit', (e) => this.submit(e));
  }

  formView() {
    const form = '<!-- html code generated by JS -->';
    return form;
  }

  renderNavList() {
    const exampleNav_HTML = document.querySelector('.example__nav__list');
    this.navList.forEach((list) => {
      const li = document.createElement('li');
      li.classList.add('example__nav__list__list-item');
      li.textContent = list;

      exampleNav_HTML.appendChild(li);
    });
  }

  renderViewArray(array) {
    array.forEach((num) => {
      const li = document.createElement('li');
      li.classList.add('example__view__list__list-item');
      li.textContent = num;
      this.numberListVeiw.appendChild(li);
    });
  }

  createArray(number) {
    let count = 0;
    const array = [];
    while (count < number) {
      array.push(++count);
    }
    return array;
  }

  removeBlockClass(HTMLNodes) {
    HTMLNodes.forEach((node) => node.classList.remove('example-block-item'));
  }

  removeAllChild(element) {
    while (element.firstChild) {
      element.removeChild(element.firstChild);
    }
  }

  submit(e) {
    e.preventDefault();
    const submitter = e.submitter;
    const submitterType = submitter.dataset.type;

    if (submitterType === 'create') {
      this.formInput.classList.add('example-block-item');
      this.deleteArrayButton.classList.remove('example-block-item');
      submitter.classList.add('example-block-item');
      this.messageVlew.style.display = 'none';
      this.numberListVeiw.style.display = 'flex';

      const value = +(this.formInput.value);
      this.formInput.blur();
      this.result = this.createArray(value);
      this.renderViewArray(this.result);
    }

    if (submitterType === 'delete') {
      this.formInput.classList.remove('example-block-item');
      this.createArroyButton_HTMLElem.classList.add('example-block-item');
      submitter.classList.add('example-block-item');
      this.messageVlew.style.display = 'block';
      this.numberListVeiw.style.display = 'none';
      this.formInput.value = '';

      this.result = [];
      this.removeAllChild(this.numberListVeiw);
    }
  }
}

const example = new Example();`

export { htmlExampleJS, cssExampleJS, jsExamlle };
